image: atlassian/default-image:2

pipelines:
    branches:
        master:
            - step:
                  name: Mirror to Github
                  script:
                      - git remote add github git@github.com:HEPTACOM/digistore24-api-client.git
                      - git push github master
